name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: phamviet/xiaozhi-hub
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Set deploy tag
        id: set-tag
        run: |
          SHA_TAG=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.tags[-1]')
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: false # change to true once you're ready to deploy'
          context: .
          file: Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      # Deploy steps